In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
x1 = np.array([1,2,3,4,5])
print(x1)

[1 2 3 4 5]


In [ ]:
np.array(3, dtype='float', ndmin=2) #object

array([[3.]])

In [ ]:
np.array([[2,4],[5,6]])

array([[2, 4],
       [5, 6]])

In [ ]:
# np array function:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.full(10, np.pi)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

In [ ]:
np.full(10, 3.0)

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [ ]:
np.linspace(5,10,8) #start,end, totalnum      `

array([ 5.        ,  5.71428571,  6.42857143,  7.14285714,  7.85714286,
        8.57142857,  9.28571429, 10.        ])

In [ ]:
np.zeros((3,5), dtype='int') #dimension, arrayno.ofelemen

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.full((3,6), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265]])

In [ ]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#special  function
np.random.random() #[0-1) tak flaot return

0.029400186470134648

In [ ]:
np.random.random(5)

array([0.09996924, 0.76426865, 0.79543956, 0.53860278, 0.15908565])

In [ ]:
np.random.random((2,3))

array([[0.31993934, 0.07397535, 0.61464885],
       [0.59393727, 0.97999819, 0.91942135]])

In [ ]:
np.random.randint(23) #(random int num low , high, size, dtype) 23)

5

In [ ]:
np.random.randint(20,100, 5)

array([46, 83, 62, 59, 83])

In [ ]:
np.random.randint(20,100,(2,3))

array([[93, 54, 51],
       [62, 39, 47]])

In [ ]:
np.random.uniform()#(random int num low , high, size) default #0-1 also more themn 1

0.6544258547372668

In [ ]:
np.random.uniform(0.3,1,1)#(random int num low , high, size) default #0-1 also more themn 1

array([0.50552407])

In [ ]:
np.random.uniform(20,10, (2,3))#(random int num low , high, size) default #0-1 also more themn 1

array([[18.76862101, 17.05254351, 13.96073874],
       [11.18290128, 16.5471581 , 16.24102524]])

In [ ]:
np.random.choice(5)

0

In [ ]:
np.random.choice((2,3,5), size=5)

array([5, 3, 2, 2, 2])

In [ ]:
np.random.choice(range(1,50), (2,3), False)

array([[ 3,  2, 32],
       [12, 17, 46]])

In [ ]:
#random array may set bana k liyah seed
np.random.seed(15)
print(np.unifrom)

In [ ]:
print(X1)
