In [1]:
 pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [20]:
import numpy as np

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

def find_primes(arr):
    prime = []
    for num in arr.flat: 
        if is_prime(num):
            prime.append(num)
    return np.array(prime)

org_array = np.random.randint(1,10, (1, 8))
prime_array = find_primes(org_array)

print(org_array)
print(prime_array)

[[8 3 1 9 3 2 2 2]]
[3 3 2 2 2]


In [32]:
np.random.seed(15)  
x = np.random.randint(1, 10, (3, 4))
print(array1)

np.random.seed(15)
y = np.random.randint(0, 10, size=(3, 4))
print(array2)

Addition = x + y
print("Matrix Addition:", Addition)


[[9 6 6 8]
 [1 8 6 7]
 [2 8 1 5]]
[[8 5 5 7]
 [0 7 5 6]
 [1 7 0 4]]
Matrix Addition: [[17 11 11 15]
 [ 1 15 11 13]
 [ 3 15  1  9]]


In [37]:
def calculateSum():
    sum = 0
    list1 = []
    for i in range(1, 7):
        x = np.random.randint(1,7)
        list1.append(x)
    for i in list1:
            sum = sum + i
            
    print(list1)
    print(sum)
    if sum>25:
        print("I Won")
        
calculateSum()

[6, 3, 3, 4, 3, 2]
21
