# **NUMPY**

NumPy is a Python library that is the core library for scientific computing in Python. It stands for Numerical Python.

It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering.

One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices.

To work with these arrays, there’s a vast amount of high-level mathematical functions operate on these matrices and arrays.

**Installation of Numpy**

In [ ]:
!pip install numpy

**Import Numpy**

Since now we are using an outside library and its installed, we will use the import keyword to access that particular library.

In [ ]:
#to import the libary
import numpy as np

**Numpy Arrays**

1. Numpy array is a grid of values, homogeneous type, and indexed.
2. It can be multi dimensional, where the number of dimensions is the rank of the array. Although Python has list data type, but Numpy is built for efficiency and speed.

In [ ]:
#using list

x1= np.array([1,3,4,5,2])

print(x1)

[1 3 4 5 2]


In [ ]:
#using tuples
x1= np.array((1,3,4,5,2))

print(x1)

[1 3 4 5 2]


**Creating a Numpy Array**

The most common method to create a Numpy array is using the constructor array. The constructor has many parameters, but we will focus on three.

* object, the sequence you want to make array from. For e.g., a list (or any collection). It can be a scalar, meaning that it can be single element as well (resulting in an 0-dimensional array).
* dtype, Keyword (optional) argument what is the type of the elements, can infer from the elements provided as object or can be specifically provided.
* ndmin, Keyword (optional) argument to specify how many minimum dimensions that array should have.

Lets look at some of its uses.

In [ ]:
np.array(3)


array(3)

In [ ]:
np.array(3, dtype='float')


array(3.)

In [ ]:
np.array(3, dtype='float', ndmin=2)


array([[3.]])

In [ ]:
np.array([[2,4],[5,6]])

array([[2, 4],
       [5, 6]])

**Numpy Zero Array**

You also have special constructors to construct specific type of arrays.

Create an array of zeros

Create an integer array of 10 elements filled with all zeros.

In [ ]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros(10) #default is float dtype

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Numpy Ones Array**

Create an array of ones

Create a integer array filled with ones.


In [ ]:
np.ones(10, dtype="int")

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones(10) #default is float dtype

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Numpy Full Array**

Create an array which is filled with pi values.


In [ ]:
np.full(10, np.pi)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

In [ ]:
np.pi

3.141592653589793

In [ ]:
#3. Create a array filled with a scalar
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
#3. Create a array filled with a scalar
np.full(10, 3.0)

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

**Numpy linspace Arrays**

Create an array with linearly spaced (equidistant) points between given interval.

create an array with 8 points equidistant between 5 and 10.


In [ ]:
np.linspace(5,10,8)

array([ 5.        ,  5.71428571,  6.42857143,  7.14285714,  7.85714286,
        8.57142857,  9.28571429, 10.        ])

In [ ]:
np.linspace(5,23,7)

array([ 5.,  8., 11., 14., 17., 20., 23.])

**Numpy Multidimensional Arrays**

We can create a multidimensional array of all these sorts as well.

Multidimensional array using nested lists.

In [ ]:
x2=np.array([[1,3,4,5],[1,5,6,7]])

print(x2)

[[1 3 4 5]
 [1 5 6 7]]


In [ ]:
#Create an float array of (3,5) elements filled with all zeros.
np.zeros((3,5), dtype="int") #default dtype is float

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#Create an int array of (3,5) elements filled with all ones.
np.ones((3,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#Create an float array of (3,6) elements filled with all pis.
np.full((3,6), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265]])

In [ ]:
# Create an identity matrix

#6. Create a 3x3 identity matrix.
np.eye(3, dtype="int") #default dtype is float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Numpy Random Arrays**

Numpy allows you to create arrays with random elements. This can be very helpful if you need some arbitrary examples of arrays to work with (Like for the lecture purposes).

There is a submodule within numpy array random that has several constructors to create a random array. We will look at some of them.
- random: Used to create random arrays containing floats.
- randint: Used to create random arrays containing integer numbers.
- uniform: Used to create random arrays containing floats uniformly distributed between given range (default is 0-1).
- choice: Used to create random arrays containing numbers from given parameter.

There are many more different options (some are very similar to the ones we discuss, with slight variations).



**Numpy random.random()**

`random.random(size=None)`

Returns an array of given size, where each element is a float between [0,1).
If size is None, it will return a scalar.



In [ ]:
np.random.random() #size is not given

0.48933535003718154

In [ ]:
np.random.random(5) #size=5, means 5 elements in numpy random array

array([0.26036871, 0.51532762, 0.57907439, 0.94467936, 0.07177695])

In [ ]:
np.random.random((2,3)) #size=(1,3), means size = 3  elements in 2 rows using numpy random array

array([[0.8269296 , 0.82708115, 0.63682565],
       [0.10036219, 0.27016487, 0.21997557]])

**Numpy random.randint()**

`random.randint(low, high=None, size=None, dtype=int)`

Returns an array of given size (default is None), where each element is an integer between [low, high).

If high is not provided, then the range is [0,low).

In [ ]:
np.random.randint(23) # one element from [0,23)

2

In [ ]:
np.random.randint(20,100) # one element from [20,100)

87

In [ ]:
np.random.randint(20,100,(1,5))  # array of (1,5) size with elements from [20,100)

array([[63, 95, 60, 54, 93]])

In [ ]:
np.random.randint(20,100,(2,4))  # array of (2,4) size with elements from [20,100)

array([[45, 88, 32, 68],
       [36, 43, 33, 47]])

**Numpy random.uniform()**

```
random.uniform(low=0.0, high=1.0, size=None)
```

Returns an array of given size (default is None), where each element is float between [low, high) and uniformly distributed.

Default values of low and high are 0.0 and 1.0 respectively.

One of the difference between random and unform is the range.

In [ ]:
np.random.uniform() #return one element between 0-1

0.051694362174372066

In [ ]:
np.random.uniform(0.3,1,1) #return one element between 0.3-1

array([0.50568437])

In [ ]:
np.random.uniform(0,1,(2,5))

array([[0.07654076, 0.6711161 , 0.94283869, 0.04019896, 0.286818  ],
       [0.01307953, 0.4722488 , 0.54478297, 0.19335406, 0.53490199]])

**Numpy random.choice()**

`random.choice(a, size=None, replace=True, p=None)`

Returns an array of given size (default is None), where each element is a member of given sequence a.

replace=True means that the same element can be chosen multiple times.

p is to set different probabilities (of being selected) to elements of a.

In [ ]:
np.random.choice(5) #make choice between 0-5


2

In [ ]:
np.random.choice([2,3,5])  #selects one element from the given list

2

In [ ]:
np.random.choice((2,3,5),size=5) #selects 5 elements from the given tuple


array([5, 3, 2, 5, 3])

In [ ]:
np.random.choice(range(1,51),(2,3),False) #generates a (2*3) array of distinct elements from the given list.

array([[ 3, 33, 34],
       [29, 45, 26]])

**random.seed()**

One function that is really important is seed function, it sets the seed of the pseudo random number generator.

It helps regenerate the same sequence of random numbers (whenever needed).

This is mostly done in experiments where you need to rerun the process with the same inputs.

In [ ]:

#not using seed
print(np.random.uniform(0,1,(1,5)))

print(np.random.uniform(0,1,(1,5)))

[[0.61189447 0.53811635 0.45312922 0.41382131 0.37977175]]
[[0.57490454 0.22837057 0.0271636  0.29505747 0.80791912]]


In [ ]:
#using seed
np.random.seed(15)
print(np.random.uniform(0,1,(1,5)))

np.random.seed(15)
print(np.random.uniform(0,1,(1,5)))

[[0.8488177  0.17889592 0.05436321 0.36153845 0.27540093]]
[[0.8488177  0.17889592 0.05436321 0.36153845 0.27540093]]


**Numpy Array Attributes**

 Numpy array have the following attributes:

- ndim (the number of dimensions),
- shape (the size of each dimension), and
- size (the total size of the array).


In [ ]:
print(x1)
print(f"x1 ndim: {x1.ndim}")
print(f"x1 shape: {x1.shape}")
print(f"x1 size: {x1.size}") #totaly,6 elements

[1 3 4 5 2]
x1 ndim: 1
x1 shape: (5,)
x1 size: 5


In [ ]:
print(x2)
print(f"x2 ndim: {x2.ndim}")
print(f"x2 shape: {x2.shape}")
print(f"x2 size: {x2.size}") #totaly,12 elements

[[1 3 4 5]
 [1 5 6 7]]
x2 ndim: 2
x2 shape: (2, 4)
x2 size: 8


**Indexing**

Numpy array indexing for 1d array is same as Python's lists.

However, Numpy nd-array indexing is slightly different from Python's nd-lists. For example:

- 2d-list elements are accessed as:[index1][index2]
- 2d-array elements are accessed as:[index1,index2]

where index1 and index2 can be indices or slices. See the following examples:


In [ ]:
print(x1)
print(x2)

[1 3 4 5 2]
[[1 3 4 5]
 [1 5 6 7]]


In [ ]:
print(x1[0],x1[4],x1[-1],x1[-2])

1 2 2 5


In [ ]:
print(x2[1,1],x2[1,0],x2[1,-4],x2[-1,-3])

5 1 1 5


**Sorting**

Numpy also has built in sort functionality.

A built-in sort function that sorts the array (ascending by default).

It is immutable function, which means that the order of the original array is not changed.


In [ ]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [ ]:
# Instead of returning the sorted list, argsort returns the lists of positions of the element in the sorted list.
i = np.argsort(x)
print(i)

[1 0 3 2 4]


**Copy of Array**

Arrays are mutable too. Thus, the assignment "=" is by reference. We can use copy() to copy the entire numpy array. For example:


In [ ]:
np.random.seed(0) # seed for reproducibility
x2 = np.random.randint(10, size=(2,4)) # Two-dimensional array
print(f'x2 is:\n{x2}')

x2_copy = x2  # new reference not actual copy

x2_copy[0,1:3]=[4,4]

print(f'x2_copy is:\n{x2_copy}')

print(f'x2 is:\n{x2}')


x2 is:
[[5 0 3 3]
 [7 9 3 5]]
x2_copy is:
[[5 4 4 3]
 [7 9 3 5]]
x2 is:
[[5 4 4 3]
 [7 9 3 5]]


In [ ]:
np.random.seed(0) # seed for reproducibility
x2 = np.random.randint(10, size=(2,4)) # Two-dimensional array
print(f'x2 is:\n{x2}')

x2_copy = x2.copy()  # it will be true copy

x2_copy[0,1:3]=[4,4]


print(f'x2_copy is:\n{x2_copy}')

print(f'x2 is:\n{x2}')

x2 is:
[[5 0 3 3]
 [7 9 3 5]]
x2_copy is:
[[5 4 4 3]
 [7 9 3 5]]
x2 is:
[[5 0 3 3]
 [7 9 3 5]]


**Reshaping**

Numpy reshape() method changes the shape of an existing array without changing its data.

Create a 1d random array of size 10.

1. Create a 1d random array of size 10.

In [ ]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10,size=10) # One-dimensional array
print(x1)

[5 0 3 3 7 9 3 5 2 4]


In [ ]:
print(x1.reshape(2,5)) #Reshape the 1d array into size 2x5.

[[5 0 3 3 7]
 [9 3 5 2 4]]


In [ ]:
# when you want numpy to estimate the other dimension
print(x1.reshape(5,-1)) #here -1, is used as a wildcard

[[5 0]
 [3 3]
 [7 9]
 [3 5]
 [2 4]]


In [ ]:
print(x1.reshape(-1,5))

[[5 0 3 3 7]
 [9 3 5 2 4]]


**Concatenate/Split**


Concatenate means joining, and Numpy's .concatenate() function is used to join two or more arrays of the same shape along a specified axis.

Numpy's .vstack() (.hstack()) can be used for row wise (column wise) joining.

Numpy's split/vsplit/hsplit methods are for breaking/splitting the array, as oppose to the concatenation.

For example:


In [ ]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([9,9,9])
print(x)
print(y)
print(z)

print(np.concatenate((x,y,z)))

[1 2 3]
[3 2 1]
[9 9 9]
[1 2 3 3 2 1 9 9 9]


In [ ]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([9,9,9])

print(np.vstack((x,y,z)))  # to vertically stack all 1d arrays

[[1 2 3]
 [3 2 1]
 [9 9 9]]


In [ ]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([9,9,9])

print(np.hstack((x,y,z)))  # to horizontally stack all 1d arrays(like concatenation)

[1 2 3 3 2 1 9 9 9]


In [ ]:
x = np.array( [1,2,3])
y = np.array([[9,8,7],
              [6,5,4]]) #y is 2dimensional array

print(np.vstack([x,y]))  # vertically stack the arrays, using square brackets

print(np.vstack((x,y)))  # vertically stack the arrays, using round brackets

[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [ ]:
y = np.array([[9,8,7],
              [6,5,4]])

z = np.array([[99],
              [99]])

np.hstack([z,y])  # horizontally stack the arrays, using either square brackets or round brackets work

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

**Vectorized Operations**

 Vectorized operations are perhaps the most crucial factor to the wide usage of Numpy library. Vectorized operations simply put are those operations that can be done on arrays without using loops.

For example:

Create a random id array, and add, subtract,multiply and divide all the elements with 5.


In [ ]:
np.random.seed(0) # seed for reproducibility
x = np.random.randint(10,size=10) # One-dimensional array
print(f"x = {x}")

print(f"x + 5 = {x + 5}") # adding 5 to each element
print(f"x - 5 = {x - 5}") # subtracting 5 to each element
print(f"x * 5 = {x * 5}") # multiply each element by 5
print(f"x / 5 = {x / 5}") # divide each element by 5
print(f"x // 5 = {x // 5}") # floor division each element by 5
print(f"x ** 2 =  {x ** 2}") #Take the square of all elements.
print(f"x % 2 =  {x % 2}") #Find remainder w.r.t 2 for all elements.


x = [5 0 3 3 7 9 3 5 2 4]
x + 5 = [10  5  8  8 12 14  8 10  7  9]
x - 5 = [ 0 -5 -2 -2  2  4 -2  0 -3 -1]
x * 5 = [25  0 15 15 35 45 15 25 10 20]
x / 5 = [1.  0.  0.6 0.6 1.4 1.8 0.6 1.  0.4 0.8]
x // 5 = [1 0 0 0 1 1 0 1 0 0]
x ** 2 =  [25  0  9  9 49 81  9 25  4 16]
x % 2 =  [1 0 1 1 1 1 1 1 0 0]


In [ ]:
# Transform the array as: $-(\frac{x}{2}+1)^2$, where $x$ is the random 1d array.
newArray=-(0.5*x+1) ** 2

print(f"Given array      : {x}")
print(f"Transformed array: {newArray}")

Given array      : [5 0 3 3 7 9 3 5 2 4]
Transformed array: [-12.25  -1.    -6.25  -6.25 -20.25 -30.25  -6.25 -12.25  -4.    -9.  ]


**Ufuncs**

A universal function (or ufunc for short) is a vectorized wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs.

Functions like:

- abs
- sqrt
- min
- max
- sum
- mean
- median

For example:



In [ ]:
x = np.array([-2,-1,0,5,6,8])

print(x) # the original array
print('-'*10)

print(np.abs(x))  # convert all elements to +ve numbers
print(np.sqrt(np.abs(x)))  # get square-roots of all abs(elements)
print(np.min(x))  # get the min value
print(np.max(x))  # get the max value
print(np.sum(x))  # get the sum of all value

print(x.mean())
print(np.median(x))

[-2 -1  0  5  6  8]
----------
[2 1 0 5 6 8]
[1.41421356 1.         0.         2.23606798 2.44948974 2.82842712]
-2
8
16
2.6666666666666665
2.5
