**Question no 01**

You are given a numpy array of integers. Write a Python function called find_primes that takes this array as input and returns another numpy array containing only the prime numbers from the original array

In [3]:
import numpy as np

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

def find_primes(arr):
    prime = []
    for num in arr.flat:
        if is_prime(num):
            prime.append(num)
    return np.array(prime)

org_array = np.random.randint(1,10, (1, 8))
prime_array = find_primes(org_array)

print(org_array)
print(prime_array)


[[2 7 2 4 8 6 4 8]]
[2 7 2]


**Question no 02**

Create a random array using randint of array size 3X4. Now using seed you need to create the same array again.

Using concept of Matrix Addition, Add both the Arrays.

In [7]:
#Solution
np.random.seed(15)
x = np.random.randint(1, 10, (3, 4))
print(x)

np.random.seed(15)
y = np.random.randint(0, 10, size=(3, 4))
print(y)

Addition = x + y
print("\n Matrix Addition: \n", Addition)


[[9 6 6 8]
 [1 8 6 7]
 [2 8 1 5]]
[[8 5 5 7]
 [0 7 5 6]
 [1 7 0 4]]

 Matrix Addition: 
 [[17 11 11 15]
 [ 1 15 11 13]
 [ 3 15  1  9]]


**Question no 03**

Suppose you are rolling a dice, you need to roll the dice.

In calculateSum() method you need to calculate the sum of result each time the dice rolled, if result is greater than 25. Print "I Won".

Note: Use random function for rolling the dice.

In [8]:
def calculateSum():
    sum = 0
    list1 = []
    for i in range(1, 7):
        x = np.random.randint(1,7)
        list1.append(x)
    for i in list1:
            sum = sum + i

    print(list1)
    print(sum)
    if sum>25:
        print("I Won")

calculateSum()

[2, 6, 4, 5, 6, 5]
28
I Won
